# Generated by Django 4.1.3 on 2023-01-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
