# Generated by Django 4.1.3 on 2023-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blogpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCarucel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to='media/')),
                ('photo2', models.ImageField(upload_to='media/')),
                ('photo3', models.ImageField(upload_to='media/')),
                ('photo4', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
