# Generated by Django 4.1.3 on 2023-02-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photocarucel_photomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomain',
            name='photo5',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
