# Generated by Django 4.1.3 on 2023-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_photomain_photo5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xarita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joy', models.CharField(max_length=500)),
            ],
        ),
    ]
